---
# tasks file for Catosplace engineering base tools

- name: Install Python and Pip
  ansible.builtin.include_tasks: python_pip.yml
  tags: python_pip

- name: Install adr-tools
  ansible.builtin.include_tasks: adr_tools.yml
  tags: adr

# Temporary Ansible Role tooling until the Ansible Engineering role is developed

- name: Manage temporary tool - yamllint
  ansible.builtin.pip:
    name: yamllint
    state: "{{ temporary_tooling_state }}"
  tags: temporary_tools

- name: Manage temporary tool - ansible_lint
  become: true
  ansible.builtin.pip:
    name: ansible-lint
    state: "{{ temporary_tooling_state }}"
  tags: temporary_tools
