---
# tasks file for Catosplace engineering base tools

- name: Include adr-tools tasks
  ansible.builtin.include_tasks: adr_tools.yml
  tags: adr

# Temporary Ansible Role tooling until the Ansible Engineering role is developed

- name: Install Pyhton is Python3
  become: true
  ansible.builtin.package:
    name: python-is-python3
    state: present
  tags: temporary_tools

- name: Install Pip
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present
  tags: temporary_tools

- name: Manage temporary tool - yamllint
  ansible.builtin.pip:
    name: yamllint
    state: present
  tags: temporary_tools

- name: Manage temporary tool - ansible_lint
  become: true
  ansible.builtin.package:
    name: ansible-lint
    state: "{{ temporary_tooling_state }}"
  tags: temporary_tools
