---
# tasks file for Catosplace engineering base tools

- name: Include adr-tools tasks
  ansible.builtin.include_tasks: adr_tools.yml
  tags: adr

# Temporary Ansible Role tooling until the Ansible Engineering role is developed

- name: Manage temporary tool - yamllint
  become: true
  ansible.builtin.package:
    name: yamllint
    state: "{{ temporary_tooling_state }}"
  tags: temporary_tools

- name: Manage temporary tool - ansible_lint
  become: true
  ansible.builtin.package:
    name: ansible-lint
    state: "{{ temporary_tooling_state }}"
  tags: temporary_tools
