---

- name: Install Pyhton is Python3
  become: true
  ansible.builtin.package:
    name: python-is-python3
    state: present
  tags: python_pip

- name: Install Pip
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present
  tags: python_pip
