---
name: Engineering Ansible Base Role

on: [push, pull_request]  # yamllint disable-line rule:truthy

permissions: read-all

# Reference information about concurrency stategy provided
# here:
# https://exercism.org/docs/building/github/gha-best-practices
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  ansible-lint:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4

      - name: Lint Yaml
        uses: frenck/action-yamllint@v1

      - name: Lint Ansible Role
        uses: ansible-community/ansible-lint-action@v6

  ansible-role-test:
    needs: ansible-lint
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4

      - run: echo "Ansible Test Completed!"
